- hosts: myworkstation
  vars_files:
    - vars/main.yml
  pre_tasks:
    - include_tasks: apt_repositories.yml
    - name: Only update apt cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
    - include_tasks: user.yml
    - name: copying condarc file
      become: yes
      copy:
        src: "{{ item.src }}"
        dest: "{{ user_home }}/{{ item.dst }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: 0644
      with_items:
        - { src: condarc, dst: .condarc }
    - name: copying gitconfig file
      become: yes
      template:
        src: "{{ item.src }}"
        dest: "{{ user_home }}/{{ item.dst }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: 0644
      with_items:
        - { src: gitconfig.j2, dst: .gitconfig }

    - include_tasks: install_packages.yml
      when: install_packages
    - include_tasks: bash_setup.yml
      when: bash_setup
    - include_tasks: jekyll_setup.yml
      when: jekyll_setup
    - include_tasks: powerline_setup.yml
      when: powerline_setup
    - include_tasks: ssh.yml
      when: ssh_setup
  roles:
    - role: docker
      become: yes
    - role: playonlinux
      become: yes
    - role: java
      become: yes
    - role: miniconda
      become: yes
      become_method: su
      become_user: "{{ user_name }}"
  post_tasks:
    - name: "ensure user part of docker group"
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
      become: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
      become: yes